import { Preset } from '../types';

export const PRESETS: Preset[] = [
  { name: "Nebula", jp: "star cloud", genre: "Duotone", type: "Flow", texture: "Smooth", direction: 135, colors: ["#F3D3E4", "#4C5FD5", "#FF8FA3", "#8B6BAE"] },
  { name: "Sunset", jp: "dusk", genre: "Neon", type: "Flow", texture: "Smooth", direction: 135, colors: ["#FF5E62", "#FF9966", "#FFD194"] },
  { name: "Aurora", jp: "polar", genre: "Neon", type: "Aurora", texture: "Smooth", direction: 45, colors: ["#00F5A0", "#00D9F5", "#7B61FF", "#0B1B3A"] },
  { name: "Celestial Sky", jp: "clouds", genre: "Neon", type: "Sky", texture: "Smooth", direction: 135, colors: ["#1A2A6C", "#B21F1F", "#FDBB2D"] },
  { name: "Draped Silk", jp: "satin", genre: "Metallic", type: "Silk", texture: "Smooth", direction: 45, colors: ["#E0C3FC", "#8EC5FC", "#4A00E0"] },
  { name: "Borealis", jp: "night", genre: "Holographic", type: "Aurora", texture: "Smooth", direction: 45, colors: ["#050C1A", "#00FF87", "#60EFFF", "#9D00FF"] },
  { name: "Candy", jp: "sweet", genre: "Pastel", type: "Flow", texture: "Smooth", direction: 135, colors: ["#FF0080", "#7928CA", "#00D4FF"] },
  { name: "Sea Glass", jp: "mist", genre: "Duotone", type: "Flow", texture: "Frosted", direction: 135, colors: ["#2E3192", "#1BFFFF", "#C9FFF4"] },
  { name: "Rose Gold", jp: "metallic", genre: "Metallic", type: "Flow", texture: "Smooth", direction: 135, colors: ["#B76E79", "#F7CAC9", "#E8B4A0"] },
  { name: "Lavender", jp: "floral", genre: "Duotone", type: "Mesh", texture: "Smooth", direction: 135, colors: ["#A18CD1", "#FBC2EB", "#E4D9FF", "#7B61FF"] },
  { name: "Moss", jp: "forest", genre: "Duotone", type: "Mesh", texture: "Grain", direction: 135, colors: ["#2F5D50", "#A3C9A8", "#E9F5DB", "#5A8F6E"] },
  { name: "Bloom", jp: "flower", genre: "Holographic", type: "Freeform", texture: "Smooth", direction: 90, colors: ["#FA8BFF", "#2BD2FF", "#2BFF88"] },
  { name: "Ember", jp: "glow", genre: "Neon", type: "Radial", texture: "Grain", direction: 90, colors: ["#FF512F", "#F09819"] },
  { name: "Golden Hour", jp: "sunset", genre: "Duotone", type: "Linear", texture: "Smooth", direction: 135, colors: ["#F6D365", "#FDA085"] },
  { name: "Coral", jp: "reef", genre: "Duotone", type: "Linear", texture: "Smooth", direction: 135, colors: ["#FF6E7F", "#BFE9FF"] },
  { name: "Gold Leaf", jp: "gold", genre: "Metallic", type: "Linear", texture: "Smooth", direction: 135, colors: ["#BF953F", "#FCF6BA"] },
  { name: "Ocean", jp: "deep", genre: "Duotone", type: "Linear", texture: "Smooth", direction: 135, colors: ["#2E3192", "#1BFFFF"] },
  { name: "Prism", jp: "rainbow", genre: "Rainbow", type: "Conic", texture: "Smooth", direction: 0, colors: ["#FF5F6D", "#FFC371", "#FFF240", "#66E46E", "#4FA7FF", "#B06AB3"] },
  { name: "Blade", jp: "edge", genre: "Duotone", type: "Blade", texture: "Film", direction: 118, colors: ["#FFFFFF", "#5C9BFF", "#FF7A2F", "#000000"], spots: [[0.30, 0.46], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5]] },
  { name: "Halo", jp: "ring", genre: "Chrome", type: "Orb", texture: "Film", direction: 0, colors: ["#FFFFFF", "#79A9FF", "#FF8A3D", "#000000"], spots: [[0.56, 0.50], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5]] },
  { name: "Horizon", jp: "horizon", genre: "Metallic", type: "Horizon", texture: "Film", direction: 0, colors: ["#FFFFFF", "#9CC4FF", "#FF8A3D", "#000000"], spots: [[0.50, 0.44], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5]] },
  { name: "Filament", jp: "fiber", genre: "Holographic", type: "Fiber", texture: "Film", direction: 150, colors: ["#FFFFFF", "#7FB0FF", "#FF8433", "#000000"], spots: [[0.62, 0.34], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5]] },
  { name: "Sakura", jp: "spring", genre: "Pastel", type: "Mesh", texture: "Smooth", direction: 135, colors: ["#FDF2F8", "#F8C8DC", "#D291BC", "#8E7CC3"] },
  { name: "Vaporwave", jp: "retro", genre: "Neon", type: "Conic", texture: "Smooth", direction: 0, colors: ["#FF00E1", "#00E5FF", "#FFD319"] },
  { name: "Matrix", jp: "code", genre: "Duotone", type: "Flow", texture: "Grain", direction: 135, colors: ["#001F0C", "#00FF41", "#00B32C"] },
  { name: "Desert", jp: "dunes", genre: "Duotone", type: "Linear", texture: "Paper", direction: 180, colors: ["#ED8F03", "#FFB75E"] },
  { name: "Iceberg", jp: "glacier", genre: "Duotone", type: "Flow", texture: "Frosted", direction: 150, colors: ["#0F2027", "#57C1FF", "#8FD3F4"] },
  { name: "Cyber Rose", jp: "neon", genre: "Holographic", type: "Mesh", texture: "Smooth", direction: 45, colors: ["#FF5FA2", "#B721FF", "#21D4FD"] },
  { name: "Pulse", jp: "heartbeat", genre: "Neon", type: "Orb", texture: "Film", direction: 0, colors: ["#FFFFFF", "#FF4E50", "#F9D423", "#000000"], spots: [[0.5, 0.5], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5]] },
  { name: "Twilight", jp: "dusk", genre: "Iridescent", type: "Flow", texture: "Smooth", direction: 150, colors: ["#355C7D", "#6C5B7B", "#C06C84"] },
  { name: "Spectrum", jp: "full color", genre: "Rainbow", type: "Linear", texture: "Grain", direction: 90, colors: ["#FF004D", "#FF8A00", "#FFEA00", "#2EE86A", "#00C2FF", "#7A00FF"] },
  { name: "Lagoon", jp: "tropical", genre: "Duotone", type: "Mesh", texture: "Frosted", direction: 45, colors: ["#00C9FF", "#5FFBF1", "#00B4D8", "#03045E"] },
  { name: "Café", jp: "warm", genre: "Pastel", type: "Mesh", texture: "Smooth", direction: 0, colors: ["#F6E7D3", "#E3C5A0", "#C79A6E", "#8C5F3A"] },
  { name: "Mint", jp: "fresh", genre: "Pastel", type: "Radial", texture: "Smooth", direction: 0, colors: ["#F2FFF7", "#BFF0D8", "#7EDBB0", "#3FB08A"] },
  { name: "Nova", jp: "supernova", genre: "Neon", type: "Orb", texture: "Film", direction: 0, colors: ["#FFFFFF", "#5C9BFF", "#FF7A2F", "#05060B"], spots: [[0.5, 0.5], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5]] },
  { name: "Crimson", jp: "velvet", genre: "Metallic", type: "Linear", texture: "Film", direction: 135, colors: ["#8E0E00", "#B3252B", "#F2CDA0"] },
  { name: "Arcade", jp: "retro", genre: "Neon", type: "Reflected", texture: "Smooth", direction: 90, colors: ["#FF3860", "#00E5FF", "#FFD319", "#7B2FF7"] },
  { name: "Juicy", jp: "fruit", genre: "Neon", type: "Linear", texture: "Smooth", direction: 135, colors: ["#FF512F", "#DD2476"] },
  { name: "Azure", jp: "sky", genre: "Duotone", type: "Linear", texture: "Smooth", direction: 135, colors: ["#2F80ED", "#56CCF2"] },
  { name: "Meadow", jp: "green", genre: "Duotone", type: "Mesh", texture: "Grain", direction: 45, colors: ["#11998E", "#38EF7D"] },
  { name: "Ultra", jp: "violet", genre: "Neon", type: "Conic", texture: "Smooth", direction: 0, colors: ["#7F00FF", "#E100FF"] },
  { name: "Noir", jp: "deep", genre: "Duotone", type: "Flow", texture: "Smooth", direction: 150, colors: ["#0F2027", "#203A43", "#2C5364"] },
  { name: "Electric", jp: "volt", genre: "Neon", type: "Linear", texture: "Grain", direction: 90, colors: ["#8E2DE2", "#4A00E0"] },
  { name: "Breeze", jp: "wind", genre: "Iridescent", type: "Flow", texture: "Smooth", direction: 135, colors: ["#FC466B", "#3F5EFB"] },
  { name: "Sapphire", jp: "gem", genre: "Duotone", type: "Mesh", texture: "Frosted", direction: 120, colors: ["#1A2980", "#26D0CE"] },
  { name: "Mars", jp: "planet", genre: "Metallic", type: "Linear", texture: "Film", direction: 135, colors: ["#E96443", "#904E95"] },
  { name: "Forest", jp: "woods", genre: "Duotone", type: "Flow", texture: "Grain", direction: 120, colors: ["#5A3F37", "#2C7744"] },
  { name: "Berry", jp: "dark", genre: "Holographic", type: "Mesh", texture: "Smooth", direction: 45, colors: ["#C94B4B", "#4B134F"] },
  { name: "Citrus", jp: "zesty", genre: "Neon", type: "Linear", texture: "Wave", direction: 135, colors: ["#F7971E", "#FFD200"] },
  { name: "Graphite", jp: "metal", genre: "Metallic", type: "Reflected", texture: "Smooth", direction: 0, colors: ["#304352", "#D4D4D4"] },
  { name: "Glacier", jp: "ice", genre: "Duotone", type: "Radial", texture: "Smooth", direction: 0, colors: ["#00B4DB", "#0083B0"] },
  { name: "Violet Sky", jp: "twilight", genre: "Pastel", type: "Mesh", texture: "Smooth", direction: 135, colors: ["#4568DC", "#B06AB3", "#E6E6FA"] },
  { name: "Amber", jp: "warm", genre: "Neon", type: "Flow", texture: "Film", direction: 135, colors: ["#F83600", "#F9D423"] },
  { name: "Honey", jp: "gold", genre: "Metallic", type: "Linear", texture: "Smooth", direction: 90, colors: ["#FFB75E", "#ED8F03"] },
  { name: "Sprout", jp: "plant", genre: "Duotone", type: "Mesh", texture: "Paper", direction: 45, colors: ["#1D976C", "#93F9B9"] },
  { name: "Dusk", jp: "evening", genre: "Duotone", type: "Flow", texture: "Smooth", direction: 150, colors: ["#4B6CB7", "#182848"] },
  { name: "Fairytale", jp: "dream", genre: "Pastel", type: "Linear", texture: "Smooth", direction: 135, colors: ["#CC95C0", "#DBD4B4", "#7AA1D2"] },
  { name: "Sunburn", jp: "beach", genre: "Neon", type: "Radial", texture: "Grain", direction: 0, colors: ["#FC4A1A", "#F7B733"] },
  { name: "Blue Lagoon", jp: "water", genre: "Duotone", type: "Flow", texture: "Frosted", direction: 135, colors: ["#00D2FF", "#3A7BD5"] },
  { name: "Sangria", jp: "wine", genre: "Metallic", type: "Flow", texture: "Film", direction: 135, colors: ["#3A6186", "#89253E"] },
  { name: "Stone", jp: "pebble", genre: "Duotone", type: "Linear", texture: "Paper", direction: 160, colors: ["#B79891", "#94716B"] },
  { name: "Peach Fuzz", jp: "soft", genre: "Pastel", type: "Radial", texture: "Smooth", direction: 0, colors: ["#FFE5D9", "#FFB199", "#FF8C94"] },
  { name: "Vapor", jp: "synth", genre: "Holographic", type: "Conic", texture: "Film", direction: 0, colors: ["#FF00E1", "#00E5FF", "#7A00FF"] },
  { name: "Ember Glow", jp: "fire", genre: "Neon", type: "Orb", texture: "Film", direction: 0, colors: ["#FFD194", "#FF512F", "#B91D1D", "#0B0505"], spots: [[0.5, 0.5], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5]] },
  { name: "Plasma", jp: "beam", genre: "Holographic", type: "Blade", texture: "Film", direction: 118, colors: ["#FFFFFF", "#9D00FF", "#00E5FF", "#05060A"], spots: [[0.30, 0.46], [0.5, 0.5], [0.5, 0.5], [0.5, 0.5]] },
  { name: "Harbor", jp: "docks", genre: "Chrome", type: "Linear", texture: "Wave", direction: 135, colors: ["#0F3443", "#34E89E"] }
];
